import type { CandidateItem } from '../types';

/** App-specific cleanup guidance. Match only known caches, never an entire profile. */
export const APP_CLEANERS = [
  { id: 'chrome', name: 'Google Chrome', color: '#83bc90', cacheRoots: ['Library/Caches/Google/Chrome'], what: 'Cached web content used by Chrome.', consequence: 'Pages may load more slowly while their caches refill. Bookmarks, passwords and browser profiles remain in their separate locations.', before: 'Quit Chrome, including background processes, before cleanup.' },
  { id: 'safari', name: 'Safari', color: '#7cbded', cacheRoots: ['Library/Caches/com.apple.Safari', 'Library/Containers/com.apple.Safari/Data/Library/Caches'], what: 'Safari’s generated cache files.', consequence: 'Web content is fetched again as you browse. This cleanup targets caches, not history, passwords or your browsing profile.', before: 'Quit Safari before cleanup. Some sandboxed folders may require Full Disk Access.' },
  { id: 'slack', name: 'Slack', color: '#c49bf0', cacheRoots: ['Library/Caches/com.tinyspeck.slackmacgap', 'Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Caches'], what: 'Local caches generated by Slack.', consequence: 'Slack rebuilds its caches and may download content again. Saved application state and preferences are outside this selection.', before: 'Quit Slack before cleanup.' },
  { id: 'spotify', name: 'Spotify', color: '#70c694', cacheRoots: ['Library/Caches/com.spotify.client'], what: 'Generated cache files stored by Spotify.', consequence: 'Spotify may fetch content again. Manage intentionally downloaded offline music inside Spotify.', before: 'Quit Spotify before cleanup.' },
  { id: 'discord', name: 'Discord', color: '#8b9cf8', cacheRoots: ['Library/Caches/com.hnc.Discord'], what: 'Cached content generated by Discord.', consequence: 'Discord rebuilds the cache as content is used again. Its separate application state is retained.', before: 'Quit Discord before cleanup.' },
] as const;

export function appCacheItems(candidates: CandidateItem[], home: string, roots: readonly string[]) {
  if (!home) return [];
  const paths = roots.map((root) => `${home}/${root}`);
  const matches = candidates.filter((c) => c.category === 'rebuildable' && c.action === 'quarantine' && paths.some((p) => c.path === p || c.path.startsWith(`${p}/`)));
  // Candidate reports may contain both a cache root and descendants. Never double-count them.
  return matches.filter((c) => !matches.some((parent) => parent.path !== c.path && c.path.startsWith(`${parent.path}/`)));
}
