// Fake Tauri backend for screenshots. Injected before the app loads; serves a made-up Mac.
(() => {
  const HOME = '/Users/alex';
  const G = 1024 ** 3, M = 1024 ** 2;
  const NOW = Math.floor(Date.now() / 1000);
  const DAY = 86400;
  const cfg = window.__DISKO_MOCK__ || {};

  // ---- tree DSL: [name, sizeGB | children[], meta?] ----
  const meta = (path) => {
    const p = path.replace(HOME, '');
    const m = (category, tag, action = 'quarantine', reason = '') => ({ category, tag, action, reason });
    if (/node_modules|\/\.next|\/target|\/build$|\/dist$/.test(p)) return m('rebuildable', 'build-output', 'quarantine', 'Generated by the project build; recreated by the next install or build.');
    if (/DerivedData/.test(p)) return m('rebuildable', 'xcode-cache', 'quarantine', 'Xcode build products and indexes.');
    if (/CoreSimulator\/Devices/.test(p)) return m('review', 'simulator-device', 'quarantine', 'Simulator device with its own apps and data.');
    if (/CoreSimulator\/Caches/.test(p)) return m('rebuildable', 'simulator-cache', 'quarantine', 'Simulator dyld and runtime caches.');
    if (/DeviceSupport/.test(p)) return m('review', 'redownloadable-apple-content', 'quarantine', 'Debug symbols for a connected device OS version.');
    if (/Archives/.test(p)) return m('review', 'release-artifact', 'quarantine', 'Xcode release archive with dSYMs.');
    if (/Library\/Caches/.test(p)) return m('rebuildable', 'app-cache', 'quarantine', 'Application cache, rebuilt on demand.');
    if (/\.npm|\.cache|\.gradle|pnpm/.test(p)) return m('rebuildable', 'dependency-cache', 'manager_command', 'Package manager cache.');
    if (/\.lmstudio|huggingface/.test(p)) return m('review', 'downloaded-model', 'quarantine', 'Downloaded model weights; large to download again.');
    if (/com\.docker/.test(p)) return m('review', 'managed-container-store', 'manager_command', 'Docker images, containers and volumes.');
    if (/Photos Library|Mail|Messages/.test(p)) return m('keep', 'managed-library', 'owner_app', 'Managed by its app; remove inside the app.');
    if (/Application Support/.test(p)) return m('keep', 'app-state', 'owner_app', 'App state and settings.');
    if (/Downloads/.test(p)) return m('review', 'downloads', 'quarantine', 'Downloaded file.');
    if (/\.git$/.test(p)) return m('keep', 'repository', 'owner_app', 'Git history.');
    return m('review', 'user-files', 'quarantine', '');
  };
  const byPath = new Map();
  const build = (spec, parent) => {
    const [name, v] = spec;
    const path = parent ? `${parent}/${name}` : name;
    const isDir = Array.isArray(v) || /\.(app|photoslibrary|fcpbundle|xcarchive)$/.test(name) || spec[2] === 'dir';
    const children = Array.isArray(v) ? v.map((c) => build(c, path)) : [];
    const own = Array.isArray(v) ? 0 : v * G;
    const total = own + children.reduce((a, c) => a + c.total, 0);
    const node = { path, name: parent ? name : 'Home', kind: isDir ? 'directory' : 'file', total, children, rest_total: 0, rest_count: 0, ...meta(path) };
    byPath.set(path, node);
    return node;
  };
  const uuid = (i) => `${(0x3f2a9c10 + i * 7919).toString(16).toUpperCase()}-${(0x4b1e + i * 13).toString(16).toUpperCase()}-4${(0x2a0 + i).toString(16).toUpperCase()}-A${(0x913 + i * 3).toString(16).toUpperCase()}-${(0x5c07d2e41b00 + i * 104729).toString(16).toUpperCase()}`;
  const sims = [6.8, 6.1, 5.9, 5.4, 4.9, 4.6, 4.2, 3.9, 3.3, 2.8, 2.4, 1.9, 1.5, 1.2, 0.8].map((s, i) => [uuid(i), [['data', s * 0.97], ['device.plist', 0.00002]]]);
  const nm = (big) => ['node_modules', [['@next', big * 0.22], ['typescript', big * 0.06], ['esbuild', big * 0.05], ['@swc', big * 0.12], ['react-native', big * 0.18], ['.pnpm', big * 0.25], ['lucide-react', big * 0.04], ['other', big * 0.08]]];
  const project = (name, big, extra = []) => [name, [nm(big), ['.git', big * 0.18], ['src', big * 0.03], ...extra]];
  const spec = [HOME, [
    ['Library', [
      ['Developer', [
        ['CoreSimulator', [['Devices', sims], ['Caches', [['dyld', 4.1], ['com.apple.CoreSimulator.SimDevice', 1.9]]]]],
        ['Xcode', [
          ['DerivedData', [['Lumen-dkhqzvwq', 6.2], ['Pocketbook-bxfmyyk', 4.8], ['WeatherKitDemo-azrt', 3.1], ['Orbit-hgqlpe', 2.2], ['ModuleCache.noindex', 1.7]]],
          ['iOS DeviceSupport', [['iPhone16,1 18.1 (22B83)', 4.3], ['iPhone16,1 17.5.1 (21F90)', 4.1], ['iPhone15,2 17.2 (21C62)', 3.6]]],
          ['Archives', [['2026-08-12', 1.9], ['2026-05-03', 1.4], ['2025-11-20', 0.9]]],
        ]],
        ['XcodeBuildMCP', [['workspaces', 3.2], ['cache', 0.9]]],
      ]],
      ['Containers', [['com.docker.docker', [['Data', [['vms', 34.6], ['log', 0.6]]]]], ['com.apple.mail', 3.1], ['com.tinyspeck.slackmacgap', 1.2], ['com.apple.Safari', 0.8]]],
      ['Application Support', [['Adobe', 8.9], ['Google', [['Chrome', 5.7]]], ['Code', 3.8], ['Slack', 2.6], ['Zed', 1.9], ['Spotify', 1.4], ['Discord', 1.2], ['Figma', 0.9]]],
      ['Caches', [['Adobe', [['After Effects', 5.2], ['Media Cache', 1.3]]], ['Homebrew', 3.1], ['com.spotify.client', 3.4], ['Google', [['Chrome', 2.6]]], ['ms-playwright', 1.9], ['com.tinyspeck.slackmacgap', 1.4], ['Yarn', 2.0], ['pip', 0.7], ['com.hnc.Discord', 0.9]]],
      ['Messages', [['Attachments', 6.1]]],
      ['Mail', 3.9],
    ]],
    ['Movies', [['Final Cut', [['Launch Edit.fcpbundle', 38.2], ['Trip 2025.fcpbundle', 22.7]]], ['Screen Recordings', [['demo-take-3.mov', 7.8], ['demo-take-2.mov', 6.4], ['standup.mov', 2.9]]], ['GoPro', 14.1]]],
    ['Pictures', [['Photos Library.photoslibrary', 68.4], ['Lightroom', 3.2]]],
    ['Developer', [
      project('lumen', 3.4, [['.next', 2.1]]),
      project('pocketbook-app', 4.6, [['ios', [['build', 3.8], ['Pods', 2.2]]], ['android', [['build', 2.7], ['.gradle', 1.1]]]]),
      project('orbit-api', 1.9, [['target', 7.9]]),
      project('marketing-site', 1.6, [['.next', 1.3]]),
      project('old-experiments', 2.8),
      project('design-system', 1.2),
    ]],
    ['Downloads', [['Xcode_16.4.xip', 9.6], ['macOS Sequoia installer.dmg', 13.4], ['DaVinci_Resolve_19.zip', 3.7], ['raw-footage.zip', 11.2], ['Figma.dmg', 0.4], ['datasets', [['coco-2017.zip', 18.9], ['imagenet-val.tar', 6.4]]], ['old-backups', 7.2]]],
    ['.lmstudio', [['models', [['qwen3-32b-mlx', 18.4], ['llama-3.3-70b-q4', 21.1], ['gemma-3-12b', 7.2]]]]],
    ['Documents', [['Taxes', 1.1], ['Clients', 14.6], ['Scans', 3.3], ['Zoom', 9.4], ['Books', 2.7]]],
    ['.cache', [['huggingface', 9.1], ['puppeteer', 1.3], ['uv', 2.2], ['pre-commit', 0.6]]],
    ['.npm', [['_cacache', 6.9], ['_npx', 3.1]]],
    ['.rustup', [['toolchains', 5.8]]],
    ['.gradle', [['caches', 4.6]]],
    ['Music', [['Music', 11.8]]],
    ['Desktop', [['Screenshots', 2.1], ['mockups', 3.6], ['untitled folder', 1.2]]],
  ]];
  const root = build(spec, null);

  const trunc = (n, depth) => depth <= 0 || !n.children.length
    ? { ...n, children: [], rest_total: n.children.length ? n.total : 0, rest_count: n.children.length }
    : { ...n, children: n.children.map((c) => trunc(c, depth - 1)) };
  const item = (n, i) => ({ id: i + 1, parent: 0, path: n.path, name: n.name, kind: n.kind, total: n.total, allocated: n.total, logical: Math.round(n.total * 0.98), category: n.category, reason: n.reason, tag: n.tag, action: n.action, cost: n.category === 'rebuildable' ? 'local-rebuild' : 'unknown', tool: null, mtime_ns: (NOW - (i * 37 % 200) * DAY) * 1e9, error: null, child_count: n.children.length });
  const children = (path) => [...(byPath.get(path)?.children ?? [])].sort((a, b) => b.total - a.total).map(item);

  const volume = { total: 994 * G, available: 31.2 * G, available_including_purgeable: 38.6 * G, used: 962.8 * G };
  const scanMeta = { root: HOME, started: NOW - 3600 - 41, finished: NOW - 3600, entries: 2841733, complete: true, db_path: `${HOME}/.disko/reports/home.sqlite`, coverage_issues: 0 };
  const info = { home: HOME, workspace: `${HOME}/.disko`, db_path: scanMeta.db_path, db_loaded: true, codex_path: '/opt/homebrew/bin/codex', codex_version: 'codex-cli 0.58.0', scan: scanMeta, volume };

  const cand = (path, category, tag, action, reason, cost = 'local-rebuild', tool = null) => {
    const n = byPath.get(HOME + path);
    return { path: HOME + path, name: path.split('/').pop(), kind: n?.kind ?? 'directory', total: n?.total ?? 1 * G, category, reason, tag, action, cost, tool };
  };
  const candidates = [
    cand('/Library/Developer/Xcode/DerivedData', 'rebuildable', 'xcode-cache', 'quarantine', 'Xcode build products, indexes and module caches. Rebuilt on the next build.'),
    cand('/Library/Developer/CoreSimulator/Caches', 'rebuildable', 'simulator-cache', 'quarantine', 'Simulator dyld shared caches. Recreated when a simulator boots.'),
    cand('/Developer/orbit-api/target', 'rebuildable', 'build-output', 'quarantine', 'Cargo build output. `cargo build` recreates it.'),
    cand('/Library/Caches/Adobe/After Effects', 'rebuildable', 'app-cache', 'quarantine', 'Rendered frame disk cache. Frames render again when needed.'),
    cand('/.npm/_cacache', 'rebuildable', 'dependency-cache', 'manager_command', 'npm content cache. npm verifies and prunes it safely.', 'network-small', 'npm cache verify'),
    cand('/Developer/pocketbook-app/ios/build', 'rebuildable', 'build-output', 'quarantine', 'iOS build folder, regenerated by the next build.'),
    cand('/Developer/pocketbook-app/node_modules', 'rebuildable', 'build-output', 'quarantine', 'Installed packages. `bun install` restores them from the lockfile.', 'network-small'),
    cand('/Library/Caches/com.spotify.client', 'rebuildable', 'app-cache', 'quarantine', 'Streaming cache. Offline downloads are managed inside Spotify.'),
    cand('/Library/Caches/Homebrew', 'rebuildable', 'dependency-cache', 'manager_command', 'Downloaded bottles and source archives.', 'network-small', 'brew cleanup --prune=all'),
    cand('/Developer/lumen/node_modules', 'rebuildable', 'build-output', 'quarantine', 'Installed packages. Restored from the lockfile.', 'network-small'),
    cand('/Developer/lumen/.next', 'rebuildable', 'build-output', 'quarantine', 'Next.js build cache.'),
    cand('/.npm/_npx', 'rebuildable', 'dependency-cache', 'quarantine', 'Temporary npx installs. Re-downloaded on next use.', 'network-small'),
    cand('/Library/Caches/Google/Chrome', 'rebuildable', 'browser-cache', 'quarantine', 'Web cache. Profiles, passwords and history are separate.'),
    cand('/Library/Caches/ms-playwright', 'rebuildable', 'dependency-cache', 'quarantine', 'Browser binaries used by Playwright tests.', 'network-large'),
    cand('/Library/Caches/Yarn', 'rebuildable', 'dependency-cache', 'manager_command', 'Yarn package cache.', 'network-small', 'yarn cache clean'),
    cand('/.cache/uv', 'rebuildable', 'dependency-cache', 'manager_command', 'uv tracks what is still referenced.', 'network-small', 'uv cache prune'),
    cand('/Library/Caches/com.tinyspeck.slackmacgap', 'rebuildable', 'app-cache', 'quarantine', 'Slack web cache.'),
    cand('/Library/Developer/Xcode/iOS DeviceSupport/iPhone15,2 17.2 (21C62)', 'review', 'redownloadable-apple-content', 'quarantine', 'Symbols for iOS 17.2. A newer version is stored for this hardware.', 'network-large'),
    cand('/Library/Containers/com.docker.docker', 'review', 'managed-container-store', 'manager_command', 'Docker disk image. Prune unused images and volumes in Docker.', 'network-large', 'docker system prune'),
    cand('/Downloads/macOS Sequoia installer.dmg', 'review', 'old-installer', 'quarantine', 'Installer image. macOS is already up to date.', 'network-large'),
    cand('/Downloads/Xcode_16.4.xip', 'review', 'old-installer', 'quarantine', 'Xcode archive. Xcode 16.4 is already installed.', 'network-large'),
    cand('/.lmstudio/models/llama-3.3-70b-q4', 'review', 'downloaded-model', 'quarantine', 'Model weights, not loaded in 4 months.', 'network-large'),
    cand('/Downloads/datasets/coco-2017.zip', 'review', 'downloads', 'quarantine', 'Large archive, last opened in March.', 'network-large'),
    cand('/Library/Developer/Xcode/Archives/2025-11-20', 'review', 'release-artifact', 'quarantine', 'Release archive. Keep if this build shipped.', 'irreplaceable'),
  ];

  const unused = (path, days, kind = 'file') => {
    const n = byPath.get(HOME + path);
    return { path: HOME + path, name: path.split('/').pop(), logical_bytes: n.total, allocated_bytes: n.total, days_inactive: days, category: n.category, reason: n.reason, last_used: new Date((NOW - days * DAY) * 1000).toISOString(), last_accessed: null, modified: new Date((NOW - (days + 20) * DAY) * 1000).toISOString(), evidence: 'spotlight_last_used', kind };
  };
  const unusedFiles = [
    unused('/Movies/Final Cut/Trip 2025.fcpbundle', 311),
    unused('/Downloads/datasets/coco-2017.zip', 204),
    unused('/Downloads/macOS Sequoia installer.dmg', 388),
    unused('/Movies/GoPro', 276),
    unused('/Downloads/raw-footage.zip', 162),
    unused('/Downloads/Xcode_16.4.xip', 121),
    unused('/Documents/Zoom', 243),
    unused('/Movies/Screen Recordings/demo-take-3.mov', 148),
    unused('/Downloads/old-backups', 517),
    unused('/Downloads/datasets/imagenet-val.tar', 204),
    unused('/Movies/Screen Recordings/demo-take-2.mov', 149),
    unused('/Downloads/DaVinci_Resolve_19.zip', 190),
  ];
  const app = (name, gb, days) => ({ path: `/Applications/${name}.app`, name: `${name}.app`, logical_bytes: gb * G, allocated_bytes: gb * G, days_inactive: days, category: 'review', reason: 'Application bundle.', last_used: new Date((NOW - days * DAY) * 1000).toISOString(), last_accessed: null, modified: null, evidence: 'spotlight_last_used', kind: 'app' });
  const unusedApps = [app('Topaz Video', 18.6, 201), app('DaVinci Resolve', 6.1, 143), app('Blender', 2.4, 322), app('Unity Hub', 1.1, 410), app('GarageBand', 2.9, 612)];

  const remnants = { schema: 1, rules: 212, generated_at: NOW - 3500, db: scanMeta.db_path, installed_apps: 146, agents: [
    { path: `${HOME}/Library/LaunchAgents/com.sketch.updater.plist`, label: 'com.sketch.updater', program: '/Applications/Sketch.app/Contents/Helpers/Updater', reason: 'Program no longer exists.' },
  ], groups: [
    { id: 'com.bohemiancoding.sketch3', name: 'Sketch', score: 0.92, confidence: 'likely', total: 2.4 * G, newest_mtime: NOW - 390 * DAY, evidence: ['No app bundle with this identifier', 'Last written 13 months ago'], members: [
      { path: `${HOME}/Library/Caches/com.bohemiancoding.sketch3`, kind: 'cache', total: 1.6 * G, newest_mtime: NOW - 390 * DAY, preselect: true, persistent: false },
      { path: `${HOME}/Library/Application Support/com.bohemiancoding.sketch3`, kind: 'state', total: 0.8 * G, newest_mtime: NOW - 400 * DAY, preselect: false, persistent: true },
    ] },
    { id: 'com.parallels.desktop.console', name: 'Parallels Desktop', score: 0.88, confidence: 'likely', total: 1.3 * G, newest_mtime: NOW - 210 * DAY, evidence: ['Uninstalled', 'Logs and caches only'], members: [
      { path: `${HOME}/Library/Caches/com.parallels.desktop.console`, kind: 'cache', total: 0.9 * G, newest_mtime: NOW - 210 * DAY, preselect: true, persistent: false },
      { path: `${HOME}/Library/Logs/Parallels`, kind: 'logs', total: 0.4 * G, newest_mtime: NOW - 211 * DAY, preselect: true, persistent: false },
    ] },
    { id: 'com.electron.notion', name: 'Notion', score: 0.71, confidence: 'confirm', total: 0.61 * G, newest_mtime: NOW - 95 * DAY, evidence: ['No app bundle found', 'Web storage present'], members: [
      { path: `${HOME}/Library/Application Support/Notion`, kind: 'state', total: 0.52 * G, newest_mtime: NOW - 95 * DAY, preselect: false, persistent: true },
      { path: `${HOME}/Library/Caches/notion.id`, kind: 'cache', total: 0.09 * G, newest_mtime: NOW - 95 * DAY, preselect: true, persistent: false },
    ] },
  ] };

  const jItem = (p, gb, present = true) => ({ original: HOME + p, quarantined: `${HOME}/.Trash/disko-x/${p.split('/').pop()}`, size: gb * G, present });
  const journals = [
    { id: 'a1', path: `${HOME}/.Trash/disko-8f2c1a/journal.json`, created_at: NOW - 2 * 3600, purged: false, total_bytes: 27.4 * G, items: [jItem('/Library/Developer/Xcode/DerivedData', 18.0), jItem('/Developer/orbit-api/target', 7.9), jItem('/Library/Caches/ms-playwright', 1.5)] },
    { id: 'a2', path: `${HOME}/.Trash/disko-51be07/journal.json`, created_at: NOW - 26 * 3600, purged: false, total_bytes: 12.2 * G, items: [jItem('/Library/Developer/CoreSimulator/Devices/7A1F20C3-91E2', 6.8), jItem('/Library/Developer/CoreSimulator/Devices/C83E11B0-4F27', 5.4)] },
    { id: 'a3', path: `${HOME}/.Trash/disko-0c93dd/journal.json`, created_at: NOW - 6 * DAY, purged: true, total_bytes: 61.3 * G, items: [jItem('/Library/Developer/Xcode/iOS DeviceSupport/iPhone14,2 16.4', 4.1, false), jItem('/Downloads/Install macOS Sonoma.app', 13.1, false), jItem('/.lmstudio/models/mixtral-8x7b', 26.4, false), jItem('/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw.old', 17.7, false)] },
  ];

  // ---- Xcode inventory ----
  const X = [];
  const simNames = [
    ['iPhone 16 Pro', 'iOS 18.1', ['Same model & OS', 'Shutdown'], 3], ['iPhone 16 Pro', 'iOS 18.1', ['Same model & OS', 'Shutdown'], 18], ['iPhone 16 Pro', 'iOS 18.1', ['Same model & OS', 'Shutdown'], 41],
    ['iPhone 15 Pro', 'iOS 17.5', ['Same model & OS', 'Shutdown'], 96], ['iPhone 15 Pro', 'iOS 17.5', ['Same model & OS', 'Shutdown'], 131], ['iPhone 15 Pro', 'iOS 17.5', ['Same model & OS', 'Shutdown'], 160],
    ['iPad Pro 13-inch (M4)', 'iPadOS 18.1', ['Shutdown'], 22], ['iPhone 15', 'iOS 17.2', ['Runtime unavailable', 'Shutdown'], 240], ['iPhone SE (3rd generation)', 'iOS 18.1', ['Shutdown'], 57],
    ['Apple Watch Series 10 (46mm)', 'watchOS 11.1', ['Shutdown'], 80], ['iPhone 14 Pro Max', 'iOS 16.4', ['Runtime unavailable', 'Shutdown'], 402], ['Apple TV 4K (3rd generation)', 'tvOS 18.1', ['Shutdown'], 190],
    ['iPhone 16', 'iOS 18.1', ['Booted'], 0], ['iPad mini (A17 Pro)', 'iPadOS 18.1', ['Shutdown'], 64], ['Apple Vision Pro', 'visionOS 2.1', ['Shutdown'], 150],
  ];
  const simSizes = [6.8, 6.1, 5.9, 5.4, 4.9, 4.6, 4.2, 3.9, 3.3, 2.8, 2.4, 1.9, 1.5, 1.2, 0.8];
  simNames.forEach(([n, os, badges, days], i) => X.push({ path: `${HOME}/Library/Developer/CoreSimulator/Devices/${uuid(i)}`, name: n, group: 'simulators', total: simSizes[i] * G, modified: NOW - days * DAY, last_booted: new Date((NOW - days * DAY) * 1000).toISOString(), subtitle: `${os} · ${uuid(i).slice(0, 8)}`, badges, blocked: badges.includes('Booted') ? 'Shut down this simulator in Xcode or Simulator before cleaning it up' : null, partial: false }));
  [['iPhone16,1 18.1 (22B83)', 4.3, ['Newest stored'], 12], ['iPhone16,1 17.5.1 (21F90)', 4.1, ['Older version'], 150], ['iPhone15,2 17.2 (21C62)', 3.6, ['Older version'], 290], ['iPhone15,2 16.4.1 (20E252)', 3.2, ['Older version'], 520], ['Watch7,5 11.1 (22R4)', 1.4, ['Newest stored'], 30]]
    .forEach(([n, gb, badges, days]) => X.push({ path: `${HOME}/Library/Developer/Xcode/iOS DeviceSupport/${n}`, name: n, group: 'support', total: gb * G, modified: NOW - days * DAY, last_booted: null, subtitle: n.startsWith('Watch') ? 'watchOS device support' : 'iOS device support', badges, blocked: null, partial: false }));
  [['Lumen', 6.2, 2], ['Pocketbook', 4.8, 9], ['WeatherKitDemo', 3.1, 188], ['Orbit', 2.2, 61], ['ModuleCache.noindex', 1.7, 1], ['SwiftUIPlayground', 1.1, 302]]
    .forEach(([n, gb, days]) => X.push({ path: `${HOME}/Library/Developer/Xcode/DerivedData/${n}-dkhqzvwq`, name: n, group: 'derived', total: gb * G, modified: NOW - days * DAY, last_booted: null, subtitle: 'Build products, indexes and logs', badges: ['Rebuildable'], blocked: null, partial: false }));
  [['workspaces/lumen-3f1a', 2.1], ['workspaces/pocketbook-9c2e', 1.1], ['cache', 0.9]]
    .forEach(([n, gb]) => X.push({ path: `${HOME}/Library/Developer/XcodeBuildMCP/${n}`, name: n.split('/').pop(), group: 'mcp', total: gb * G, modified: NOW - 12 * DAY, last_booted: null, subtitle: 'Agent workspace copy', badges: [], blocked: null, partial: false }));
  [['CoreSimulator caches', 4.1], ['xcodebuild caches', 1.9], ['Xcode caches', 0.7]]
    .forEach(([n, gb]) => X.push({ path: `${HOME}/Library/Caches/${n}`, name: n, group: 'caches', total: gb * G, modified: NOW - 3 * DAY, last_booted: null, subtitle: 'Generated cache · rebuilt when needed', badges: ['Rebuildable'], blocked: null, partial: false }));
  [['2026-08-12', 1.9], ['2026-05-03', 1.4], ['2025-11-20', 0.9]]
    .forEach(([n, gb]) => X.push({ path: `${HOME}/Library/Developer/Xcode/Archives/${n}`, name: n, group: 'archives', total: gb * G, modified: Math.floor(new Date(n).getTime() / 1000), last_booted: null, subtitle: 'Lumen · Pocketbook release archives', badges: [], blocked: null, partial: false }));
  const xcode = { items: X.sort((a, b) => b.total - a.total), warnings: [] };

  const appItem = (path, name, group, gb, subtitle) => ({ path: HOME + path, name, group, total: gb * G, modified: NOW - 20 * DAY, last_booted: null, subtitle: subtitle ?? (group === 'version' ? 'Older agent installation' : 'Generated cache · rebuilt when needed'), badges: [], blocked: null, partial: false });
  const inv = (items) => ({ total: items.reduce((a, i) => a + i.total, 0) * 1.35, potential: items.reduce((a, i) => a + i.total, 0), partial: false, items, warnings: [] });
  const appStorage = {
    adobe: inv([appItem('/Library/Caches/Adobe/After Effects', 'After Effects disk cache', 'cache', 5.2), appItem('/Library/Application Support/Adobe/Common/Media Cache Files', 'Media Cache Files', 'cache', 1.3), appItem('/Library/Application Support/Adobe/Common/Peak Files', 'Peak Files', 'cache', 0.4)]),
    helium: inv([appItem('/Library/Caches/net.imput.helium/Default/Cache', 'Default · Cache', 'cache', 0.9), appItem('/Library/Caches/net.imput.helium/Default/Code Cache', 'Default · Code Cache', 'cache', 0.3)]),
    cursor: inv([appItem('/.local/share/cursor-agent/versions/2026.08.21-a91c2e', '2026.08.21-a91c2e', 'version', 0.56), appItem('/.local/share/cursor-agent/versions/2026.09.02-4be1f0', '2026.09.02-4be1f0', 'version', 0.58), appItem('/Library/Application Support/Cursor/Cache', 'Desktop cache', 'cache', 0.7)]),
    claude: inv([appItem('/.local/share/claude/versions/2.1.270', '2.1.270', 'version', 0.2), appItem('/.local/share/claude/versions/2.1.274', '2.1.274', 'version', 0.2), appItem('/Library/Caches/com.anthropic.claudefordesktop', 'Desktop cache', 'cache', 0.35)]),
  };

  const scans = [
    { path: scanMeta.db_path, file: 'home.sqlite', root: HOME, started: scanMeta.started, finished: scanMeta.finished, entries: scanMeta.entries, rows: scanMeta.entries, mode: 'quick', complete: true, size_bytes: 412 * M, active: true },
    { path: `${HOME}/.disko/reports/disk.sqlite`, file: 'disk.sqlite', root: '/', started: NOW - 9 * DAY, finished: NOW - 9 * DAY + 190, entries: 5120331, rows: 5120331, mode: 'thorough', complete: true, size_bytes: 781 * M, active: false },
  ];

  const search = (q) => [...byPath.values()].filter((n) => n.name.toLowerCase().includes(q.toLowerCase())).sort((a, b) => b.total - a.total).slice(0, 40).map(item);
  const largest = [...byPath.values()].filter((n) => n.kind === 'file').sort((a, b) => b.total - a.total).slice(0, 40).map(item);

  const handlers = {
    get_app_info: () => info,
    load_disk_overview: () => ({ root: HOME, volume, items: children(HOME), db_loaded: true, entry_count: scanMeta.entries, category_totals: { rebuildable: 92 * G, review: 240 * G, keep: 190 * G, protected: 12 * G } }),
    query_folder_children: ({ path }) => children(path),
    get_subtree: ({ path, depth }) => trunc(byPath.get(path) ?? root, depth ?? 9),
    get_path_info: ({ path }) => byPath.has(path) ? item(byPath.get(path), 0) : null,
    search_entries: ({ query }) => search(query),
    get_largest_files: () => largest,
    get_candidates: () => candidates,
    get_unused_files: () => unusedFiles,
    get_unused_apps: () => unusedApps,
    get_remnants: () => remnants,
    list_codex_models: () => ({ default_model: 'gpt-5.5', default_effort: 'medium', models: [{ slug: 'gpt-5.5', display_name: 'GPT-5.5', description: 'Default', efforts: ['low', 'medium', 'high'], default_effort: 'medium', priority: 1 }] }),
    list_scans: () => scans,
    get_app_cleanup_storage: ({ appId }) => appStorage[appId],
    get_xcode_storage: () => xcode,
    list_quarantine_journals: () => journals,
    get_volume: () => volume,
    get_coverage_issue_count: () => 0,
    check_full_disk_access: () => true,
    get_launch_options: () => ({ start_page: cfg.page ?? 'explore', start_path: cfg.path ?? HOME, advanced: cfg.advanced ?? true, autoscan: null }),
  };

  let cb = 1;
  const callbacks = new Map();
  window.__TAURI_EVENT_PLUGIN_INTERNALS__ = { unregisterListener: () => {} };
  window.__TAURI_INTERNALS__ = {
    metadata: { currentWindow: { label: 'main' }, currentWebview: { windowLabel: 'main', label: 'main' } },
    transformCallback: (fn) => { const id = cb++; callbacks.set(id, fn); return id; },
    unregisterCallback: (id) => callbacks.delete(id),
    convertFileSrc: (p) => p,
    invoke: async (cmd, args = {}) => {
      if (cmd.startsWith('plugin:event|listen')) return cb++;
      if (cmd.startsWith('plugin:')) return null;
      const h = handlers[cmd];
      return h ? JSON.parse(JSON.stringify(h(args))) : null;
    },
  };
})();
